version: 2
jobs:
  build:
    docker:
      - image: savoirfairelinux/odoo-ci:11.0
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo

    working_directory: /mnt/extra-addons

    steps:
      - checkout
      - run:
          name: Wait for PostgreSQL
          command: dockerize -wait tcp://localhost:5432 -timeout 5m

      - run:
          name: Odoo install base
          command: odoo --db_host=localhost --db_user=odoo --db_password=odoo -d circleci_test --workers=0 -i base --stop-after-init

      - run:
          name: Odoo install repos modules
          command: coverage run /usr/bin/odoo --db_host localhost --db_user odoo --db_password odoo -d circleci_test --workers=0 --test-enable -i $(find . -maxdepth 1 -type d ! -name '.*' -printf '%f,') --stop-after-init
